---

- name: Update /etc/hosts in guests
  hosts: all

  tasks:

    - name: Add hosts to /etc/hosts
      lineinfile:
        path: /etc/hosts
        state: present
        # on each host, for every host:
        #  if there are more than two network interfaces:
        #   Print the IP address of the first interface that is neither the
        #   default interface, nor loopback.
        #   if a domainname is defined:
        #    Print the hostname + domainname
        #   Print the hostname
        line: '{{
          hostvars[item][
            "ansible_" ~ (hostvars[item].ansible_interfaces
              | difference ([
                  "lo",
                  hostvars[item].ansible_default_ipv4.alias,
                ]))[0]
          ]["ipv4"]["address"]
        }} {{
          (hostvars[item].ansible_domain != "")
            | ternary (
                item ~ "." ~ hostvars[item].ansible_domain ~ " ",
                "",
              )
        }}{{
          item
        }}'
        regexp: ' {{ item }}$'
      become: true
      when: ( hostvars[item].ansible_interfaces | count ) > 2
      with_items:
        - '{{ play_hosts | sort }}'
